# Generated by Django 4.2.5 on 2023-09-19 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('place_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_eaten', models.PositiveIntegerField(default=0)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('favorite_dish', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
