# Generated by Django 4.2.5 on 2023-09-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestaurantdata',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
