# Generated by Django 4.2.5 on 2023-09-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userrestaurantdata_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrestaurantdata',
            name='place_id',
        ),
    ]
